### ISSUE TITLE
Deployment does not show in android device when going to "Find Maps Arround Me"

### ISSUE THREAD

**Issue by EUNACAL** [ushahidi/Ushahidi_Android#106]
I have set up an ushahidi deployment. I try to access it from my android device going to "Find Maps Arround Me" but the deployment does not show. Any idea why?

**Comment by GemmaNash** [comment]
So this is the same issue I have... does anyone know how to fix it? Thanks!

**Comment by eyedol** [comment]
@EUNACAL Did you have public listing enabled at the ushahidi backend? It has be enabled before the deployment shows up on the backend. Since this is not a bug, I'm going to close this issue. We can have further discussion on the [forums](forums.ushahidi.com)

**Comment by GemmaNash** [comment]
Hi
Yes, our listing is public on crowdmap.
Gemma
