### ISSUE TITLE
app crashes when opening my deployment, map not showing

### ISSUE THREAD

**Issue by antsemot** [ushahidi/Ushahidi_Android#109]
hello

i've set up the application by changing the google maps api key, but when i run the app in the emulator, the maps are not showing (the only things shown just the grids and the google logo). the app also does not retrieve any of the categories for the deployment

this is the url of my deployment: mapping.fbb.utm.my/fly

**Comment by eyedol** [comment]
Make sure you're running it off the Google maps api key of your debug keystore.
