### ISSUE TITLE
No core\bin\core.jar ?

### ISSUE THREAD

**Issue by steadyjay** [ushahidi/Ushahidi_Android#110]
I created a new project in eclipse with the existing code, but I get 

Project 'Coretest' is missing required library: 'C:\Users\J\Desktop\Ushahidi_Android-develop\Core\bin\core.jar'

I cannot see a core.jar in the core\bin folder?

**Comment by eyedol** [comment]
This should be created automatically during the build process.

**Comment by djehauti** [comment]
I solved this by adding Core as a library to Coretest, however, see my post #112 I may be doing that completely wrong

**Comment by eyedol** [comment]
Glad to hear you got it sorted. Closed!
