### ISSUE TITLE
Category only displaying time picker

### ISSUE THREAD

**Issue by mikecamponovo** [ushahidi/Ushahidi_Android#114]
When trying to submit a report you have to select a category. However, when you pick the category button a time picker shows up, not the categories I set up on my crowdmap site.
I'm testing the application on Android 4.2.1 and 4.2.2 with app version 3.1.5.

**Comment by eyedol** [comment]
Is this running on a stock Android? Behaves well at my end.

**Comment by mikecamponovo** [comment]
Henry,
The two phones have a stock Android install. Could it be a problem with my Crowdmap instance? I tested it on my iPhone and using the web submission and it works perfectly. The crowdmap site is https://geog581.crowdmap.com. If you want to try it out I would greatly appreciate your feedback.

Thanks,
Michael

**Comment by eyedol** [comment]
Funky. It's not a problem with your install. I was able to successfully sent in a report to your crowdmap deployment. Could you send me a screenshot? also which device are you on? Tablet or phone? Brand?

**Comment by mikecamponovo** [comment]
Henry,
The device we checked this morning is a Samsung Galaxy S3 smart phone. The
Map information we used was:
Title: geography 581 test map (is the title case sensitive?)
URL: https://geog581.crowdmap.com

I'm actually wondering if the phone isn't even connecting to the site
properly. Are the log in details different for the Android app than they
are for the iPhone app? The app on the android phone does not display any
of the reports that are displayed on my iPhone when I successfully connect.
I've attached a screenshot of what we see when we try and click on the
category button on the android phone and a screen capture from the same
screen on the iPhone.

Michael
[image: Inline image 2]
[image: Inline image 3]

**Comment by mikecamponovo** [comment]
One more screenshot showing the lack of reports and that none of the
categories are visible when trying to filter those categories:
[image: Inline image 1]

**Comment by mikecamponovo** [comment]
And here are the "Map Details" from the Android App Screen:
[image: Inline image 1]

**Comment by eyedol** [comment]
@mikecamponovo  Thanks for the info. None of the images got attached. Could you respond via github.com instead so the images can show.

**Comment by mikecamponovo** [comment]
Sure.

**Comment by mikecamponovo** [comment]
Henry,
Here are the screen captures:
![](https://f.cloud.github.com/assets/4050578/340983/4643b280-9d62-11e2-871f-93f79088d012)
![Screenshot_2013-04-04-10-18-04](https://f.cloud.github.com/assets/4050578/340984/466997ca-9d62-11e2-949f-bc1e1e57df20.png)
![Screenshot_2013-04-04-10-23-54](https://f.cloud.github.com/assets/4050578/340985/466a0610-9d62-11e2-9ef7-999f5d618a3b.png)
![Screenshot_2013-04-04-10-33-37](https://f.cloud.github.com/assets/4050578/340986/4686bd96-9d62-11e2-8cc3-4a7cb1fef467.png)

**Comment by eyedol** [comment]
Funky. Mind sending me logs. I can't reproduce it from my end. You can install [CatLog](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat) It will record the logs, then you can send it to me. 

Once you've CatLog installed, run Ushahidi Android till the error shows up. Then save the log. You can attach it to this thread. Thanks.

**Comment by mikecamponovo** [comment]
Henry,
You have to use https instead of http (using the crowdmap site online or the iPhone app the "s" is automatically added). If you try to connect but don't add the "s" then the app crashes. When you restart the app it doesn't actually connect to the crowdmap site even though it looks like it is connected. I think this explains why the already submitted reports were not visible and why the category picker didn't work. When we noticed the difference and added the "s" we weren't hitting the refresh button on the app, we just clicked on the map name, so it wasn't ever connecting. When we hit the refresh button it connected to the site, the reports were visible, and the category picker started working. Thank you for your help and patience.

Michael

**Comment by eyedol** [comment]
Glad to hear it's working. I'll fix the HTTP to HTTPS issue. Thanks for the feedback.

**Comment by eyedol** [comment]
Fixed!
