### ISSUE TITLE
Adding maps is crashing 

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/Ushahidi_Android#117]
Trying to add multiple maps, crashing
1. Searched location -maps near me. added two, when to add parksideworks.crowdmap.com. It crashed. 
2. restarted app, tried again with this map, crashed
   3.picked roncsymemories.crowdmap.com - crashed.
3. Successfully added thedemocracityproject.org.
4. tried highheelslofi.crowdmap.com, crashed.

Is Crowdmap working with the Android app?

**Comment by eyedol** [comment]
Damn! This thing is on a roll eh. 

Did you add the `https` protocol when adding the URL. Also, when exactly does it crash? Just after you hit the `Ok` button to add the URL or when you attempt to sync after you successfully add the URL?

@heatherleson Yes Crowdmap works with the Android app.

**Comment by heatherleson** [comment]
The action I was taking was : Search "Find maps near me" and click on the various crowdmaps near me. 

Tried to manually add them. it appears to work.

Tried to remove "accessibleto.crowdmap.com" to test. This crashed the tool. The map remains in my list.
Tried to remove "snowintoronto.crowdmap.com" to test. This also crashed the tool. The map remains in my list.

**Comment by eyedol** [comment]
Are you running Ushahidi Android v3.1.5 ?

**Comment by heatherleson** [comment]
yes

**Comment by eyedol** [comment]
@heatherleson  I have made bunch of fixes and improvement to how maps are loaded and added. I'll make an apk available for testing.
