### ISSUE TITLE
Don't shows google maps in application.

### ISSUE THREAD

**Issue by ml1ght** [ushahidi/Ushahidi_Android#118]
Hello. I use eclipse for compile project "Ushahidi_Android-sdk-integration". This is one of the projects which I can to compile. Other projects there are develop, master I can't compile.
My problem in sdk-integration project - don't show google maps in activities. In logCat message: 
<b>Google Maps Android API(23089): Authorization failure. 
Google Maps Android API(23089): Failed to load map.  Could not contact Google servers.</b>

How I can resolve this problem? Thanks.

**Comment by ml1ght** [comment]
Problem was in Api key in my application. Now all works fine.

**Comment by eyedol** [comment]
Glad to hear it's solved. I have merged `sdk-integration` into `develop` and I believe you should be able to compile without any issue.
