### ISSUE TITLE
Unable to load images when navigating reports in ViewReportActivity 

### ISSUE THREAD

**Issue by reddy2401** [ushahidi/Ushahidi_Android#121]
Application, unable load images when navigating using arrow symbols in ViewReportActivity.
Even reports having images in list page then not loading images in ViewReportActivity when using navigating symbols.

**Comment by eyedol** [comment]
@reddy2401 Does it load the images when you swipe between the screens

**Comment by reddy2401** [comment]
@eyedol  No, But all images are loading  before preparing List Screen. All fetched reports images are available in device cache .

**Comment by eyedol** [comment]
@reddy2401 Update your code. Made some changes that fixed that yesterday.

**Comment by eyedol** [comment]
@reddy2401 after updating the code, are you able to reproduce this error? I want to close this issue.

**Comment by reddy2401** [comment]
@eyedol  issue rectified in latest code. You can close the issue.
Thanks.

**Comment by eyedol** [comment]
Thanks
