### ISSUE TITLE
Android app crashing

### ISSUE THREAD

**Issue by aoduor** [ushahidi/Ushahidi_Android#127]
Via @ggodby
" Hello,
I have tried to use ushahidi from two different Android phones (Sony xperia X10 and Nexus 4) and the results are the same. The app will only work on the demo.ushahidid.com site. When I try to update a map on crowdmap.com or my own installation at map.oldstrathconatimes.com the app crashes every time."

**Comment by aoduor** [comment]
Hey @ggodby, what version of the app are you running?

Pinging @eyedol

**Comment by eyedol** [comment]
@ggodby which crowdmap deployment were you trying to update?. Also, I cannot reach http://map.oldstrathconatimes.com/api?task=incidents It redirects to the home page.

**Comment by aoduor** [comment]
Hmmm, @eyedol, http://map.oldstrathconatimes.com/api?task=version also redirects to the homepage. Also, @ggodby, when using a crowdmap deployment, make sure your url starts with https:// and not http://

**Comment by aoduor** [comment]
Narrowed this down to an issue with clean URLs, have a look at http://map.oldstrathconatimes.com/index.php/api?task=version. @ggodby, try enabling clean URLs via your settings page in the admin panel and let us know how it goes?

**Comment by eyedol** [comment]
@ggodby If it's a server side configuration then check this wiki entry https://wiki.ushahidi.com/display/WIKI/Enabling+Clean+URLs 

I don't expect the app to crash when there is no clean URL.

Good catch @aoduor

**Comment by ggodby** [comment]
Hello Angela,
   That worked fine. I am using NGINX on the server side and once I 
enabled clean URLs my Android Ushahidi app was able to connect and 
upload reports.
Cheers
G.

Gavin Godby
GGN Solutions Inc.
10521 78 Avenue               phone: (780) 439-8948
Edmonton, Alberta T6E 1P3
