### ISSUE TITLE
Application crashes when upload photo in a report from photo galery.

### ISSUE THREAD

**Issue by junixbr** [ushahidi/Ushahidi_Android#133]
Applications crashes when upload photo, from photo gallery, in a report.

**Comment by eyedol** [comment]
@junixbr Which version? Works fine on my phone.

**Comment by junixbr** [comment]
I've got from the last stable.

**Comment by eyedol** [comment]
@junixbr from the play store?

**Comment by junixbr** [comment]
Yes, exactly.

**Comment by eyedol** [comment]
@junixbr  Could you give step by step on how to reproduce it. Things looks good from my end.

**Comment by junixbr** [comment]
For example:
1- I start a report
2- I get a picture from photo gallery
3- when I try to upload the report, the application crashes.

**Comment by eyedol** [comment]
@junixbr Is there a way you can grab the crash report? I still can't reproduce it.

**Comment by junixbr** [comment]
eyedol, I have no idea why, but now is working fine!
I don't know if there is a new release that my phone updated.
Anyway, thank you very much.

**Comment by eyedol** [comment]
@junixbr Funky. I'm working on a new update. I'll ping you for testing to see if it re-appears?

**Comment by junixbr** [comment]
Feel free to contact me anytime.

=)
