### ISSUE TITLE
App crashes when syncing my deployment

### ISSUE THREAD

**Issue by Lunkster** [ushahidi/Ushahidi_Android#138]
My deployment (v. 2.7) on Amazon EC2 worked as a charm on Android, but suddenly it chrashes when syncing against my deployment. Working ok on the Ushahidi demo site, but not anymore on my own. Tested with two different Samsung and Android versions (Wildfire S and Galaxy SIII 4G). The app still works on iOS against the same deployment. Therefore the problem should lie within the Android app. But as already mentioned, it did work ok on the Android app up until yesterday. The deployment is located at kajakplatser.se, but as I having trouble getting clean URLs the apps has to connect to http://54.244.121.148
Suggestions anyone?

I can however send in a report through the app

Can't use catlog on Jelly bean...

**Comment by Lunkster** [comment]
Catlog from Samsung Wildfire S, and it seems it's syncing for a time until it fails....

---

06-02 12:02:58.111 E/MetadataRetrieverClient(   73): failed to extract an album art
06-02 12:02:58.131 D/MediaProvider( 1499): thumbnail original width 200, height 198
06-02 12:02:58.131 D/MediaProvider( 1499): thumbnail 1st resize width 200, height 198, mAlbumSize=320
06-02 12:02:58.302 I/com.ushahidi.android.app.api.ReportsApi( 2549): downloading... http://kajakochfritid.se/ ReportId: 47
06-02 12:02:58.342 D/MediaProvider( 1499): Put album art to caches, d.album_id= 13, size= 5
06-02 12:02:58.382 I/com.ushahidi.android.app.api.ReportsApi( 2549): downloading... http://www.guardian.co.uk/travel/2010/may/15/camping-expeditions-adventures-kayaing-walking ReportId: 45
06-02 12:02:58.832 D/MediaScanner( 1499): setMimeType mimeType= audio/mpeg
06-02 12:02:59.233 D/MediaScanner( 1499): setMimeType mimeType= audio/mpeg
06-02 12:02:59.283 I/com.ushahidi.android.app.api.ReportsApi( 2549): downloading... http://www.vasteraskanot.se ReportId: 39
06-02 12:02:59.393 I/com.ushahidi.android.app.api.ReportsApi( 2549): downloading... 2013_06_02_10_02_59.jpg ReportId: 38
06-02 12:02:59.413 D/StatusBarService(  207): updateIcon slot=data_connection index=18 viewIndex=12 old=StatusBarIcon(pkg=com.android.systemui id=0x7f0200a1 level=0 visible=true num=0 ) icon=StatusBarIcon(pkg=com.android.systemui id=0x7f020075 level=0 visible=true num=0 )
06-02 12:02:59.453 W/dalvikvm( 2549): threadid=22: thread exiting with uncaught exception (group=0x400205a0)
06-02 12:02:59.453 D/MediaScanner( 1499): setMimeType mimeType= audio/mpeg
06-02 12:02:59.463 E/AndroidRuntime( 2549): FATAL EXCEPTION: AsyncTask #1
06-02 12:02:59.463 E/AndroidRuntime( 2549): java.lang.RuntimeException: An error occured while executing doInBackground()
06-02 12:02:59.463 E/AndroidRuntime( 2549):     at android.os.AsyncTask$3.done(AsyncTask.java:200)
06-02 12:02:59.463 E/AndroidRuntime( 2549):     at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:274)
06-02 12:02:59.463 E/AndroidRuntime( 2549):     at java.util.concurrent.FutureTask.setException(FutureTask.java:125)
06-02 12:02:59.463 E/AndroidRuntime( 2549):     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:308)
06-02 12:02:59.463 E/AndroidRuntime( 2549):     at java.util.concurrent.FutureTask.run(FutureTask.java:138)
06-02 12:02:59.463 E/AndroidRuntime( 2549):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
06-02 12:02:59.463 E/AndroidRuntime( 2549):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
06-02 12:02:59.463 E/AndroidRuntime( 2549):     at java.lang.Thread.run(Thread.java:1027)
06-02 12:02:59.463 E/AndroidRuntime( 2549): Caused by: java.lang.NullPointerException
06-02 12:02:59.463 E/AndroidRuntime( 2549):     at com.ushahidi.android.app.api.ReportsApi.getReportList(ReportsApi.java:106)
06-02 12:02:59.463 E/AndroidRuntime( 2549):     at com.ushahidi.android.app.api.ReportsApi.saveReports(ReportsApi.java:149)
06-02 12:02:59.463 E/AndroidRuntime( 2549):     at com.ushahidi.android.app.ui.tablet.ListReportFragment$RefreshReports.doInBackground(ListReportFragment.java:637)
06-02 12:02:59.463 E/AndroidRuntime( 2549):     at com.ushahidi.android.app.ui.tablet.ListReportFragment$RefreshReports.doInBackground(ListReportFragment.java:1)
06-02 12:02:59.463 E/AndroidRuntime( 2549):     at android.os.AsyncTask$2.call(AsyncTask.java:185)
06-02 12:02:59.463 E/AndroidRuntime( 2549):     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
06-02 12:02:59.463 E/AndroidRuntime( 2549):     ... 4 more
06-02 12:02:59.473 W/ActivityManager(  119):   Force finishing activity com.ushahidi.android.app/.ui.phone.ReportTabActivity
06-02 12:02:59.483 I/com.ushahidi.android.app.util.Util( 2549): onPause
06-02 12:02:59.513 I/com.ushahidi.android.app.util.Util( 2549): onActivityResult
06-02 12:02:59.513 I/com.ushahidi.android.app.util.Util( 2549): onRestart
06-02 12:02:59.513 I/com.ushahidi.android.app.util.Util( 2549): onStart
06-02 12:02:59.513 I/com.ushahidi.android.app.util.Util( 2549): onResume
06-02 12:02:59.693 W/SchedPolicy( 2549): add_tid_to_cgroup failed to write '' (Invalid argument); background=0
06-02 12:02:59.793 D/dalvikvm( 2549): GC_CONCURRENT freed 840K, 48% free 4261K/8135K, external 508K/1344K, paused 6ms+12ms
06-02 12:02:59.923 D/MediaScanner( 1499): setMimeType mimeType= audio/mpeg
06-02 12:03:00.043 I/com.ushahidi.android.app.util.Util( 2549): onStop
06-02 12:03:00.133 I/com.ushahidi.android.app.util.Util( 2549): onDestroy

**Comment by eyedol** [comment]
I suspect the return of `null` values via the API. I'll look into it

**Comment by eyedol** [comment]
@Lunkster this has been fixed in this commit #136. Closing

**Comment by Lunkster** [comment]
Upgraded app and tested, worked fine. Great job!
