### ISSUE TITLE
Whitelabelled app locking into demo map list

### ISSUE THREAD

**Issue by andrewcarreiro** [ushahidi/Ushahidi_Android#149]
To reproduce this bug:
1. I've white-labelled a new app based on Beijing on the develop/ branch
2. Start the app
3. Open the left drawer
4. Hit 'Admin'
5. Open the left drawer
6. Hit 'Maps'
7. The maps list only shows the Ushahidi Demo map, despite deployment_url being set to a particular string.

**Comment by eyedol** [comment]
@andrewcarreiro  Thanks for reporting this. I suspect your deployment URL isn't validating. How did you pass it to the `deployment_url` variable.

**Comment by andrewcarreiro** [comment]
The deployment variable is set in theme.xml like so:
`<string name="deployment_url">https://trashswag.com</string>`

To clarify, at steps 2-4, it shows the report list with only items from my deployment. Once I get to step 7, it shows the list of deployments where the only item is the Ushahidi demo.

I'm not sure if this may affect the current situation, but my Google Maps API is not yet set up.

**Comment by eyedol** [comment]
@andrewcarreiro I get what is going on. When you set the `deployment_url` value, the map list view is not supposed to show at all. So the menu item for `Maps` in the navigation drawer should be disabled as well. Looking into it.

**Comment by eyedol** [comment]
@andrewcarreiro made some changes to the nav drawer. Could you confirm this is fixed? Get the latest develop code.

**Comment by andrewcarreiro** [comment]
The drawer appears to be entirely removed now; was that intentional?

**Comment by eyedol** [comment]
Yeah. It doesn't fit well with the navigation tabs and Google's design guideline discourages using it with the navigation tabs

**Comment by andrewcarreiro** [comment]
Understood. Thanks for looking into this!
