### ISSUE TITLE
Starting activity com.ushahidi.android.app.SplashScreen crashed

### ISSUE THREAD

**Issue by bernEsp** [ushahidi/Ushahidi_Android#39]
When you start an example of this app you get this error: 
E/AndroidRuntime(652): java.lang.RuntimeException: Unable to instantiate application com.ushahidi.android.app.MainApplication: java.lang.ClassNotFoundException: com.ushahidi.android.app.MainApplication in loader

**Comment by bernEsp** [comment]
This issue is caused by an error in core library manifest if the project eclipse name and manifest project name are different you get this error.

**Comment by WeSLGT** [comment]
I just ran into this issue and specifically fixed it by changing my whitelabel themes AndroidManifest.xml package name to "com.ushahidi.android.app" from com.<whitelabelname>.android.app
