### ISSUE TITLE
2.9.3 does not collect reports or show map

### ISSUE THREAD

**Issue by evoltech** [ushahidi/Ushahidi_Android#40]
Initial tests of release 2.9.3 do not show reports or map info.  Looking at the server logs I do not see the device making any requests.  What is the last known working version?

**Comment by eyedol** [comment]
@evoltech the last known working version has been 2.9.3 Not sure what the issue might be. Maybe get the logs from Android side to see what going on?

**Comment by evoltech** [comment]
I attached the adb debugger this morning and started collecting some logs.  I saw some messages which looked like exceptions about the google maps.  I decided to uninstall the application and reinstall so that I could collect a better log dump for this issue, but when I reinstalled it everything seemed to work.  I tried a few different deployment urls and the only issue I was able to generate was where the deployments that I entered listed in the Deployments intent did not seem to respond when being clicked on, but after continuing to click they responded.  So maybe this issue is only reproducible on a first install?

I have heard other folk with androids report that they had a similar issue as me, but I am not sure how to test this now.

**Comment by eyedol** [comment]
@evoltech  I made a [2.9.4](https://github.com/ushahidi/Ushahidi_Android/zipball/v2.9.4) release this week which fixes Google maps API key issue and added Spanish translation. Please keep using the app and let me know if you come across any issue. Thanks

**Comment by evoltech** [comment]
Thanks for your continued work and attentiveness.
