### ISSUE TITLE
Reports created offline aren't synced to Crowdmap when connectivity is available

### ISSUE THREAD

**Issue by zucche** [ushahidi/Ushahidi_Android#49]
The reports you create when internet connection isn't immediately available are supposedly synced to your Crowdmap deployment when the connectivity becomes available again.
It seems this isn't currently working on my Ushahidi Android app.

Here are the steps I follow:
- have a Crowdmap deployment already set in the Ushahidi app
- turn on GPS (and wait some time)
- turn off WIFI (I didn't test this on 3G yet)
- start the Ushahidi app
- add a report including Title, Description, Category, automatic geolocation
- press the Send button (you are notified the report has been saved to local storage, and you're told to sync to the online instance when connectivity will be available again)
- minimize/close the app and enable WIFI
- start the Ushahidi app
- press the Sync button and wait until "all reports have been fetched" shows up

What happens:
No reports show up in the moderation queue at my Crowdmap deployment.

Notes:
when the internet connection comes back and I run the Ushahidi app so that it syncs and sends the report, sometimes the app just crashes. Sometimes it doesn't crash, but the report just doesn't show up anyway in Crowdmap.

This happens with Ushahidi 2.9.4.
I use a Nexus S with Android 4.0.3 (official ICS update, manually installed).

**Comment by eyedol** [comment]
@zucche  -- I'll look into this further.

**Comment by eyedol** [comment]
Fixed
