### ISSUE TITLE
Connectivity with crowdmap issue

### ISSUE THREAD

**Issue by bfazen** [ushahidi/Ushahidi_Android#54]
Whenever I try to add a new report on Ushahidi Android app, I get the toast:

```
Failed to Send Report. Check to see if you filled all required fields.
```

I have filled all the required fields though, and it seems like it is serverside... debugging it gives

```
extractPayLoadJSON(): New 003
```

which I believe indicates a serverside issue... Is there a setting I need to activate on my crowdmap site? Is there some other issue?  I am running a newly downloaded Ushahidi Android app on Ideos u8150 on Safaricom in Kenya to interface with crowdmap.  Also, not sure if I should be posting here or on ushahidi forums-- sorry if this is the wrong place...

**Comment by eyedol** [comment]
Yeah it's a server side issue. Use this quick hack to turn it off. Change line 118 of application/libraries/api/My_Report_Api_Object.php from

if ($post->validate())

to

if ($post->validate(FALSE))

**Comment by bfazen** [comment]
sorry tad green on all things ushahidi... i am not running my own server, just hoping to send reports to crowdmap.com.  how do i go about changing My_Report_Api_Object.php on the crowdmap server? is that possible to do for my specific site?

thanks.

**Comment by eyedol** [comment]
@bfazen -- No you can't do that on your own. Should be fixed with crowdmap soon.
