### ISSUE TITLE
Can't submit incident after upgrade Usahidi web to master !!

### ISSUE THREAD

**Issue by AhmedSalem** [ushahidi/Ushahidi_Android#55]
Dears, 

I have a  problem after upgrading Ushahidi web to the latest version , When submit incident and filling all required fields

Get the Message (Failed to send report.Check to see if you filled all required fields.)

Our Ushahidi deployment available on http://www.zabatak.com

Can any one submit Incident on that link ??

**Comment by eyedol** [comment]
Could you upgrade to the latest version 2.4 of Ushahidi web? There was an issue with the API which affected the mobile apps.
