### ISSUE TITLE
Categories don't recognise hierarchy

### ISSUE THREAD

**Issue by rediguana** [ushahidi/Ushahidi_Android#58]
If you have implemented a nested hierarchy on Ushahidi web, the Android Ushahidi application does not recognise this hierarchy. Additionally, it renders the top level title, after its children. E.g. if you have a top level Cat 1, that has two children Cat 1A and Cat 1B, then the order they appear in the Android app is: Cat 1A, Cat 1B, Cat 1. Two things should really happen.
1. The list should be order in the correct order, in this example Cat 1, Cat 1A, Cat 1B. Looking at the data returned via apl?task=categories, the Android app appears to be rendering the category list in the reverse order.
2. It would be visually useful to see children titles indented from the parent above, so as to clearly identify the parent-children relationship.

**Comment by eyedol** [comment]
@rediguana  I'll have to look into this especially regarding indenting the child categories. I'll leave this still opened for now.

**Comment by eyedol** [comment]
@rediguana Fixed!
