### ISSUE TITLE
Offline draft reports are not uploading photos

### ISSUE THREAD

**Issue by rediguana** [ushahidi/Ushahidi_Android#59]
I have just been testing the offline functionality. I have found that when a photo is taken when in an offline state, that the photo is not uploaded to the Ushahidi server once sync occurs back in network coverage/wifi.

To reproduce:
1. Disable wifi/mobile data on the phone.
2. Create a report (at this point a draft is saved).
3. Add a photo (afterwards the draft is saved again).
4. Send the report.
5. Enable wifi/mobile data on the phone.
6. Sync.

Result:
The report is uploaded to the Ushahidi server correctly, but the photo has not been uploaded.

**Comment by eyedol** [comment]
Fixed in 3.0.0
