### ISSUE TITLE
Report upload failed ....

### ISSUE THREAD

**Issue by sfboy** [ushahidi/Ushahidi_Android#62]
Everytime by Upload shows up following toasts:
1. Saved
2. Uploading
3. Failed

That error message is in ReportFragment.java R.string.failed

**Comment by eyedol** [comment]
Keep resending. It fails if the connection fails at some point when doing the upload. It eventually gets sync. Please confirm this.

**Comment by sfboy** [comment]
thanks for your response.

I checked it many times and still have the same issue. My internet and wifi connections are actually excellence. 

But i can upload Checkin and comment without any issue, but uploading report doesn't work.

If you download last updated version ushahidi app from google play, you will face the same issue.

Hope, you will fix this asap.

**Comment by eyedol** [comment]
Which deployment are you uploading to? So I can test it from my end.

**Comment by sfboy** [comment]
http://udo dot codelab48 dot com

**Comment by eyedol** [comment]
Weird. I just submitted a report via the the emulator. Confirm if you can see a test report from Accra.

**Comment by sfboy** [comment]
I will make for you video file tomorrow, actually i have tested android 2.1 phone and ics 4.03. I tried to upload report via simulator i didn't work. Also it shows after send action automatically toast.saved and after that uploading progress with animation and toast.failed no reports too see on web site. I can't log in now to website and check your uploaded report from the mobile phone. I will check it tomorrow and give you feedback asap and make a video for reducing failed.report issue.

**Comment by sfboy** [comment]
Your report is attached and i accepted it. Which version did you use to upload that one? actually i tried many times last version 3.00

Also as i promised you, i created video, pls find below link:

http://www.youtube.com/watch?v=PDXAsENn_y8

**Comment by eyedol** [comment]
Could you install catalog https://play.google.com/store/apps/details?id=com.nolanlawson.logcat

Then run the app when it crashes, attach the crash report here.

**Comment by eyedol** [comment]
There is no log report about Ushahidi crash. Not sure if you recorded the crash after attempting to upload?

**Comment by sfboy** [comment]
how about report upload failed?

**Comment by eyedol** [comment]
That is what I'm trying to fix. Things look good on my end. 
Try and fill in all the required fields and then attempt to upload.

**Comment by sfboy** [comment]
i tired that way and exactly then happens this error failed, did you see the video to the end. After crash situation it happens 4:40 in video. can you send me your source code via email: tumurr at gmail.com.

I woul like to test your end .... copare your and my end? is that possible?

**Comment by eyedol** [comment]
@sfboy  -- Try this build and let me know how it goes. https://github.com/ushahidi/Ushahidi_Android/Ushahidi.3.0.1-alpha1.apk/qr_code

**Comment by BlueLion99** [comment]
The problem persists.

I already had a completed entry in the forum ...

**Comment by Xentar** [comment]
I have the same issue. Tried in 3.0, 3.0.1 and got the saved-uploading-failed.
When i did a test with 2.9, 2.6 and 2.0 all worked fine.
Tested in a Samsung galaxy S with android 2.3.3 and in 2 tablets, one with 2.2 and the other with 3.2
All the tests were done with 3g and WiFi connection (just in case)

**Comment by eyedol** [comment]
@BlueLion99 and @Xentar  could you try sending me a log report using [catlog](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat). Also which deployments are you testing against?

**Comment by Xentar** [comment]
Logcat: http://www.reanimados.com/logcat_and_device_info.zip
Tested in the demo and in the one i installed on my server: www.reanimados.com/gps 
The version installed on reanimados is the last build.

In other topic, Eyedol, is there a place i can download the 2.9 version source code for iphone/android? I have some issues trying to open it on my eclipse (the last build), but the real reason is that i like more the GUI of that version than the current.

**Comment by eyedol** [comment]
@Xentar you can find the [2.9.x](https://github.com/ushahidi/Ushahidi_Android/tree/2.9.4) branch [here](https://github.com/ushahidi/Ushahidi_Android/tree/2.9.4). What don't you like about the 3.0.0 UI. 

Regarding the issue you're facing. Catch me on IRC and let fix it. freenode.net #ushahidi as eyedol

**Comment by Xentar** [comment]
Thanks! Well, the 3.0 is more minimalist and have some nice things, but the 2.9- versions are more graphical, the dashboard and the icons give it a more "friendly" look. What im going to miss of the 3.0 version is the map category list and the report interface.

About my issue, thanks for the offer, if i get stuck going to join you in IRC. I'm a newbee developer, so i'm sure i'm just setting something bad in eclipse.

**Comment by eyedol** [comment]
@Xentar I just sent a test report to your deployment without an issue. Not sure what's causing the failure from your device.

**Comment by BlueLion99** [comment]
Request code 200 but get back the JSON data is:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <script type="text/javascript">var NREUMQ=NREUMQ||[];NREUMQ.push(["mark","firstbyte",new Date().getTime()]);</script>
<title>Geohazard</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="https://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700" rel="stylesheet" type="text/css">
    <script type="text/javascript">var _sf_startpt=(new Date()).getTime()</script><link rel="stylesheet" type="text/css" href="https://c683652.ssl.cf2.rackcdn.com/media/css/jquery-ui-themeroller.css" />
<link rel="stylesheet" type="text/css" href="https://c683652.ssl.cf2.rackcdn.com/themes/default/css/style.css" />
<link rel="stylesheet" type="text/css" href="https://geohazard.crowdmap.com/themes/unicorn/css/_default.css" />
<link rel="stylesheet" type="text/css" href="https://c683652.ssl.cf2.rackcdn.com/media/css/openlayers.css" />
<link rel="stylesheet" type="text/css" href="https://c683652.ssl.cf2.rackcdn.com/media/css/global.css" />
<link rel="stylesheet" type="text/css" href="https://c683652.ssl.cf2.rackcdn.com/media/css/jquery.jqplot.min.css" />

<script type="text/javascript" src="https://c683652.ssl.cf2.rackcdn.com/media/js/OpenLayers.js"></script>

<script type="text/javascript">OpenLayers.ImgPath = 'https://c683652.ssl.cf2.rackcdn.com/media/img/openlayers/';</script><script type="text/javascript" src="https://c683652.ssl.cf2.rackcdn.com/media/js/ushahidi.js"></script>

<script type="text/javascript" src="https://c683652.ssl.cf2.rackcdn.com/media/js/jquery.js"></script>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.min.js"></script>

<script type="text/javascript" src="https://c683652.ssl.cf2.rackcdn.com/media/js/jquery.pngFix.pack.js"></script>

<script type="text/javascript" src="https://c683652.ssl.cf2.rackcdn.com/media/js/jquery.timeago.js"></script>

<script type="text/javascript" src="https://maps.google.com/maps/api/js?v=3.2&amp;sensor=false"></script><script type="text/javascript" src="https://c683652.ssl.cf2.rackcdn.com/media/js/selectToUISlider.jQuery.js"></script>

<script type="text/javascript" src="https://c683652.ssl.cf2.rackcdn.com/media/js/jquery.jqplot.min.js"></script>

<script type="text/javascript" src="https://c683652.ssl.cf2.rackcdn.com/media/js/jqplot.dateAxisRenderer.min.js"></script>

<script type="text/javascript" src="https://c683652.ssl.cf2.rackcdn.com/media/js/global.js"></script>

<script type="text/javascript">
                        
                        </script>       



<meta name="robots"            content="index,follow" />
<meta name="description"       property="og:description" itemprop="about" content="Mapping natural hazards reported by Geohazard users" />
<meta property="fb:app_id"     content="335510229830429" />
<meta property="og:type"       content="ushahidi_crowdmap:deployment" />
<meta property="og:url"  ...

**Comment by eyedol** [comment]
There is an issue with the server side then. What happens if you submit a report via the web form ? also which deployment are you using to test?

**Comment by BlueLion99** [comment]
I have written an HTML form and try this to send a POST. Request code is 200 but the data is not displayed.

On the report form of Crowdmap he registered the report and will also be shown.

**Comment by BlueLion99** [comment]
Here is the HTML form:

```
   <form action="https://geohazard.crowdmap.com/" method="post">
        <p>Task: <input type="text"name="task" value="report"/></p>
        <p>Titel: <input type="text"name="incident_title" value="Test Title"/></p>
        <p>Description: <input type="text" name="incident_description" value="Test Description"/></p>
        <p>Date: <input type="text" name="incident_date" value="08/05/2012"/></p>
        <p>Hour: <input type="text" name="incident_hour" value="9"/></p>
        <p>Minute: <input type="text" name="incident_minute" value="34"/></p>
        <p>AM/PM: <input type="text" name="incident_ampm" value="am"/></p>
        <p>Category: <input type="text" name="incident_category" value="3"/></p>    
        <p>Latitude: <input type="text" name="latitude" value="52.52"/></p>
        <p>Longitude: <input type="text" name="longitude" value="13.46"/></p>
        <p>Location: <input type="text" name="location_name" value="Berlin"/></p>
        <p>Verified: <input type="text" name="incident_verified" value="1"/></p>
        <p>Active: <input type="text" name="incident_active" value="1"/></p>
        <p><input type="submit" value="Senden"></p>
    </form>
```

**Comment by eyedol** [comment]
It looks like your deployment is blocking report submission. I can't get to https://geohazard.crowdmap.com/reports/submit it redirects to the main page.

**Comment by ojovoz** [comment]
Hi there. Same problem here: using Ushahidi v3.0.0 on an HTC Desire (OS 2.2) ... I can create a report, but upload always fails. I'm trying to send it to this deployment: http://kerouac.crowdmap.com . Also: when I try to take a picture with the camera, the app crashes. Thanks for looking into this.

**Comment by sfboy** [comment]
this issue is fixed by version 3.02, where to find source code of v.3.02

**Comment by eyedol** [comment]
@sfboy glad to hear that fixes your issue. For the source code, check the v3.0.2 tag

**Comment by sfboy** [comment]
thank you for your quick respone, but by compiling comes to this error message:

something is wrong with SplashScreenActivity on line 58

you will see it when you compile it

**Comment by sfboy** [comment]
error message screenshot:

http://imageshack.us/photo/my-images/715/splashissue.jpg/

**Comment by BlueLion99** [comment]
Hello ...

Dispatch by HTC Desire with Android 2.3.3 works with the new version 3.0.2. However, on a Samsung Galaxy Nexus with Android 4.1.1 it does not work.

Shipping with Ushahidi app.

**Comment by sfboy** [comment]
i imported aws & merge from libraries folder and then core but when i compile ushahidi theme, it doesn't show splash or reportactivity tab.

**Comment by sfboy** [comment]
i tied also following solution but it doesn't work for me.
http://android.foxykeep.com/dev/how-to-fix-the-classdefnotfounderror-with-adt-17

something is wrong, first i have imported abs project to eclipse and then mergeadapter, both were in libraries folder.

And then i have imported core project. After that ushahidi theme. everything looks fine also no errors are to see.

By compiling the project comes sometimes above mentionend error message in log file window, otherwise it shows popup, which shows needed to force close etc... and nothing to see in lof file window.

I can make for you step by step guide video, if you want to see it.

**Comment by eyedol** [comment]
@sfboy since this is not related to this issue, could you move it to the forum?

**Comment by sfboy** [comment]
sure.
