### ISSUE TITLE
Categories don't show

### ISSUE THREAD

**Issue by slabo** [ushahidi/Ushahidi_Android#66]
Thanks for coding this app, an essential tool in the Ushahidi toolbox. 

I installed Ushahidi on a private hosting provider, and so far everything is working just fine so far.

Tried out the iPhone app, had to borrow one for a few minutes, everything looked just fine, was able to add a report, browse reports, filter by categories ..

On Android, on my HTC GSM Hero phone at least, categories don't show when I press the down arrow when viewing the map. Also, categories don't show when I try to add a report.

Is there anything wrong with my site or something wrong with Ushahidi Android app?

**Comment by eyedol** [comment]
Since it works well on the iPhone app, your site seems to be fine. What deployment are you testing against? Which android version are you running?

**Comment by slabo** [comment]
Using latest versions in both site and android. 

Well I think it was a connection issue. Not necessarily a fault with Ushahidi, and nothing wrong with my DSL connection. But this phone is not always in the mood. I kept hitting refresh and a few times later all hickups cleared :D 

Also, the application crashed a few times when trying to upload a photo, could a laggy connection crash the app?

I tried on another phone, all worked out perfectly. Is there anything you can do to notify the user of an internet connection problem? This way they won't blame the app

**Comment by eyedol** [comment]
@slabo  Try this one let me know how it goes https://github.com/ushahidi/Ushahidi_Android/Ushahidi.3.0.1-alpha1.apk/qr_code
