### ISSUE TITLE
Ush 2.5 & Mobile 3.0 - Galaxy S iii

### ISSUE THREAD

**Issue by KirkM0rris** [ushahidi/Ushahidi_Android#69]
lat/lon is reversed when report uploads to platform. Appears correctly in mobile app before upload. On upload I'm in Antartica :0

**Comment by eyedol** [comment]
Probably there is a flip between lat and lon variable call. I'll look into this further.

**Comment by heatherleson** [comment]
HI Henry, this issue is still occurring: 
 http://uchaguzi.co.ke/admin/reports?status=a  (two examples in the deployment)

eg
Latitude: -74.641778   Longitude: 40.650894
500, hills dr, bedminster, united states

Please advise
heather

**Comment by eyedol** [comment]
@heatherleson  This is fixed in the v3.0.2 release. Upgrade. Could you confirm if it's working for you?

**Comment by KirkM0rris** [comment]
@eyedol Fixed! Thank you.http://uchaguzi.co.ke/admin/reports/edit/82 Please delete report when fix verified.

**Comment by KirkM0rris** [comment]
fixed  http://uchaguzi.co.ke/admin/reports/edit/82

thanks

On Sun, Sep 16, 2012 at 3:29 PM, Heather Leson notifications@github.comwrote:

> HI Henry, this issue is still occurring:
> http://uchaguzi.co.ke/admin/reports?status=a (two examples in the
> deployment)
> 
> eg
> Latitude: -74.641778 Longitude: 40.650894
> 500, hills dr, bedminster, united states
> 
> Please advise
> heather
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ushahidi/Ushahidi_Android/issues/69#issuecomment-8598026.

## 

Kirk Morris

Standby Task Force
+1 347 871-5014
Skype: km5050
Twitter: @Jasper_Johns
Website: blog.standbytaskforce.com

**Comment by eyedol** [comment]
@KMsbtf Thanks. Going to close this issue
