### ISSUE TITLE
Macedonian Translation

### ISSUE THREAD

**Issue by TamaraAtanasoska** [ushahidi/Ushahidi_Android#70]
I have translated the application on Transiex. I have installed the application and I am trying to find a way how to switch English with Macedonian but I can't find. What do I need to do?

Thanks in advance.

**Comment by eyedol** [comment]
@TamaraAtanasoska You have to switch that from the phone's Language and Input settings. Did you build the app with Macedonian translation  installed?

**Comment by eyedol** [comment]
I'm turning this into an issue to officially add the translation from [transifex](https://www.transifex.com/projects/p/ush_Android/language/mk_MK/) to the repo

**Comment by TamaraAtanasoska** [comment]
Ok I will have that in mind when it will be integrated. Thanks.
