### ISSUE TITLE
No report upload/view possible when setting deployment to private

### ISSUE THREAD

**Issue by FSeitz** [ushahidi/Ushahidi_Android#71]
When I set my deployment as private in the settings of the Ushahidi Web Platform (for providing a login page) it is not possible to view or upload any reports with the mobile version. Is there any possiblity to provide a login page for the web platform and nevertheless being able to view/upload reports with the mobile version? Or is it possible to add a login for the mobile version too to fix this authentication problem?

**Comment by eyedol** [comment]
@FSeitz at the moment, private deployment doesn't expose the API. There is an upcoming fix for that. Once that is shipped, the mobile apps will implement it.

**Comment by FSeitz** [comment]
@eyedol Thanks for your answer, I'm waiting for this to come :)

Greetings, Fabian
