### ISSUE TITLE
Version 3.02 issue

### ISSUE THREAD

**Issue by sfboy** [ushahidi/Ushahidi_Android#75]
By compiling the version 3.02 source code, there's following issue

http://imageshack.us/photo/my-images/542/splashissue.jpg/

**Comment by sfboy** [comment]
any feedback?

**Comment by Magaz** [comment]
Is there any possibilities to add some very useful features: AutoSyns,  AutoSync Frequency, Background notifications like in Beijing 2.9.5 for example

Also what I` d like to add to App is background checkin mode..with some frequency

Thank you for your work and best regards!

**Comment by eyedol** [comment]
@sfboy What do you have in your manifest file for this

```
<activity
            android:name="com.ushahidi.android.app.activities.SplashScreenActivity"
            android:theme="@android:style/Theme.Black.NoTitleBar" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
</activity>
```
