### ISSUE TITLE
Version 2.9.4 image scale blurry issue

### ISSUE THREAD

**Issue by sfboy** [ushahidi/Ushahidi_Android#78]
Hello,

I also started to develop on version 2.9.4, because after my opinion this version works stable.

There's a little issue on 2.9.4, which i can't solve the issue since 5 days ago. 

The report pictures are scaled to android phone, but the picture is blurry.

I looked solution for this in goolge, but i didn't find some helpful posts. Therefore i please you guys, help me to solve this one.

Looking forward.

**Comment by sfboy** [comment]
Pls help me eyedol one last time, i can't get this solved. I tried many things.

The pictures are blur, when we get the bitmaps from phone, because i checked my gallery and then found the downloaded pictures, they are good quality. But when i see those pictures in app, then it's blur.

**Comment by sfboy** [comment]
pls pls help me or give me just a direction, where should i exactly look?

**Comment by sfboy** [comment]
hello eyedol, can you help me to solve this one

**Comment by sfboy** [comment]
i will pay for your service, is that fair?

**Comment by sfboy** [comment]
pls pls help me?

**Comment by sfboy** [comment]
hello, eyedol, this issue is very urgent and i would like to pay for your service. thank you.

**Comment by eyedol** [comment]
@sfboy are you working with the 2.9.4 branch? I don't maintain it anymore. I'll point you to the right code so you solve the issue.

**Comment by sfboy** [comment]
yes, i am working on it and thank you for your quick response, Pls point me to the right code & i keep try to solve this.

Thank you for your helps and i am appreciated.
