### ISSUE TITLE
1< images issue

### ISSUE THREAD

**Issue by sfboy** [ushahidi/Ushahidi_Android#80]
When i upload 1< pictures, it will show in report view there's 3 pictures and it shows in image previewer same pictures.

**Comment by sfboy** [comment]
when a report has 2 or more pictures, it shows every time first picture.

**Comment by sfboy** [comment]
something is wrong with ImageViewStwichworker,

**Comment by eyedol** [comment]
@sfboy are you working with 2.9.4?

**Comment by sfboy** [comment]
@eyedol i meant at version 3.0.2

i am still working on 2.9.4 & 3.0.2, because 3.0.2 sync process at splashscreen takes more time and sometimes it doesn't work in offline mode.

Also at 3.0.2, they pictures are not correct, in preview. It shows every time the first picture, no matter how many pictures are uploaded to the report.

**Comment by eyedol** [comment]
Could you provide more detail on how to reproduce the issue. See more information here on to report a bug -- http://goo.gl/XHbfR It make it easier to track the bug down.
