### ISSUE TITLE
Picture upload fails 

### ISSUE THREAD

**Issue by eyedol** [ushahidi/Ushahidi_Android#84]
@mrl-gt reported this via email

I noticed after saving a new report, the subsequent upload fails quiet
frequently,
so I recorded method traces to pinpoint the cause.
It seems that this is caused by a race condition in ListReportFragment.

start     end       th  name

---

---

2920463   3109766   20
com/ushahidi/android/app/ui/tablet/ListReportFragment.uploadPendingReports
2920468   3109674   20
com/ushahidi/android/app/adapters/ListPendingReportAdapter.pendingReports
2920476   2920484   20
com/ushahidi/android/app/models/ListReportModel.<init>
2920487   3109647   20
com/ushahidi/android/app/models/ListReportModel.loadPendingReports
2994594   3049297   1
com/ushahidi/android/app/adapters/ListPendingReportAdapter.getView
3031027   3031965   1
com/ushahidi/android/app/adapters/ListPendingReportAdapter$Widgets.<init>
3033991   3045698   1
com/ushahidi/android/app/adapters/ListPendingReportAdapter.fetchCategories
3033998   3034007   1
com/ushahidi/android/app/models/ListReportModel.<init>
3109650   3109672   20
com/ushahidi/android/app/models/ListReportModel.getReports

Below is a simplified excerpt of ListPendingReportAdapter.
Comments map the above call times to code.

``` java
public class ListPendingReportAdapter {

  private ListReportModel mListReportModel;

  // 1. @2920468 [20], method exit @3109674
  public List<ListReportModel> pendingReports() {

    // 2. @2920476 [20], mListReportModel is now instance A
    mListReportModel = new ListReportModel();

    // 3. @2920487 [20]
    final boolean loaded = mListReportModel.loadPendingReports();

    if (loaded) {

      // 6. @3109650[20], getReports() called on instace B instead of
A, which did not call loadPendingReports()
      return mListReportModel.getReports(context);
    }
    return null;
  }

  // 4. @3033991 [1], method exit @3045698
  public String fetchCategories(int reportId) {

    // 5. @3033998 [1], mListReportModel is now instance B
    mListReportModel = new ListReportModel();

    // rest of method body omitted
  }
}
```

These calls were triggered when ListReportFragment resumes from adding report.
fetchCategories() was called by the UI thread when ListView is populating items.
pendigReports() was called by the upload task's background thread.

Test Environment:
Motorola Defy+ & Nexus S, with Ushahidi App from the Play store & my own build,
This issue was recreated several times.

Setting mListReportModel to a local variable in pendingReports() seems
to make this issue disappear,
but I'm not sure if it's a good solution?
Please let me know if there's anything I can help to fix this issue.

**Comment by eyedol** [comment]
@mrl-gt See if this persist with this 54bca6d commit

**Comment by ghost** [comment]
@eyedol I tested with the current develop branch and the issue still exists.  I think it's because 54bca6d changes `ListFetchedReportAdapter`, but the traces indicate that the race condition occurs while concurrently accessing `ListPendingReportAdapter`.  I applied similar changes to `ListPendingReportAdapter` and the issue seems to be resolved (about 10 successful consecutive uploads).  My commit is here: https://github.com/mrl-gt/Ushahidi_Android/commit/b3987bb1168805b60690c5166d40fdd709d0ad7a

**Comment by eyedol** [comment]
@mrl-gt  Okay I just pushed my changes -- 1b9397bbb8. Confirm this is fixed so I can confidently close this ticket.

**Comment by ghost** [comment]
@eyedol Looking deeper into the code it seems that 1b9397b results in the background thread getting correct list of pending reports, but when preparing to upload the pending report it will sometimes run into another race condition.  

The background thread needs to fetch a pending report's category to send to the web server, and the UI thread needs a report's category data to display on screen.  This again results in possible interleaved calls to `CategoryDao.fetchCategoryByReportId`, as the following trace shows:

```
        th  start   end     class           name                     
        --  ------  ------  --------------  -------------------------
  a     10  555364  618332  CategoryDao     fetchCategoryByReportId  
  b     10  556522  556593  AbstractCursor  <init>                   
  c     10  598224  614562  AbstractCursor  moveToFirst              
  d     1   605303  617475  CategoryDao     fetchCategoryByReportId  
  e     1   606030  606122  AbstractCursor  <init>                   
  f     1   607444  609670  AbstractCursor  moveToFirst              
        1   609674  609687  AbstractCursor  isAfterLast              
        1   609690  611729  CategoryDao     cursorToEntity           
        1   611886  611900  AbstractCursor  isAfterLast              
        1   611903  613381  CategoryDao     cursorToEntity           
        1   613519  613533  AbstractCursor  isAfterLast              
        1   613536  615258  CategoryDao     cursorToEntity           
  g     10  614582  618132  AbstractCursor  isAfterLast              
        1   615397  615411  AbstractCursor  isAfterLast              
        1   615414  616872  CategoryDao     cursorToEntity           
        1   616900  616915  AbstractCursor  isAfterLast              
        1   616922  616979  AbstractCursor  close                    
        10  618138  618186  AbstractCursor  close
```

This doesn't occur very frequently, so it's rather hard to reproduce.  When it occurs incorrect value for categories are reproduced for the pending report.  I think the problem boils down to CategoryDao (and other Daos in the same package) uses class fields to store intermediate values, and will create race conditions when called concurrently.

**Comment by ghost** [comment]
@eyedol Here is a possible workaround: https://github.com/mrl-gt/Ushahidi_Android/commit/daaf80a20f3065c503c82533f83834cec0d18634 If the list of pending reports is prepared in the UI thread, interleaved calls to Dao classes can be avoided.

**Comment by eyedol** [comment]
@mrl-gt I have been trying to reproduce this myself but it's not happening for me. I see you understand the issue deeper than I do. I wonder how you're tracing it? If https://github.com/mrl-gt/Ushahidi_Android/commit/daaf80a20f3065c503c82533f83834cec0d18634 fixes the issue, I'm happy to merge this if you send me a pull request

**Comment by ghost** [comment]
@eyedol Regarding reproducing the issue, I discovered an easier way to trigger interleaved calls:  
1. turn on airplane mode
2. select a deployment and add a few reports
3. go back and forth from the list of deployments to the selected deployment
The app should exit due to `ConcurrentModificationException`  pretty quickly.  I discovered this while working on the "upload photo" feature.

The trace results are produced using method profiling.  More info [here](http://developer.android.com/tools/debugging/ddms.html#profiling) and [here](http://developer.android.com/tools/debugging/debugging-tracing.html).

I tested https://github.com/mrl-gt/Ushahidi_Android/commit/daaf80a20f3065c503c82533f83834cec0d18634 and it seems to make `ConcurrentModificationException` disappear.  If it's ok with you, I'll incorporate the fix in my `open_geosms` branch and send you a pull request when Open GeoSMS features are finished.  That way I don't have to do an extra merge with your `develop` branch.

**Comment by eyedol** [comment]
Thanks for this. I'll look deeper into the issue. Also let me know when you issue a pull request I'm happy to merge your changes.

**Comment by eyedol** [comment]
Changes merged
