### ISSUE TITLE
Can't install via Google Play on JB 4.1.2

### ISSUE THREAD

**Issue by evansims** [ushahidi/Ushahidi_Android#86]
@jetherton just brought this to our attention in Skype and I've confirmed it on my Nexus 7 as well;

![](http://evn.li/KL0g/Screen%20Shot%202012-10-22%20at%206.37.02%20PM.png)

**Comment by ptressel** [comment]
Here's a way to ask for SMS permission without disallowing install on a wifi-only tablet -- set required to false for the telephony feature. This allows using the same mainfest on phones and on wifi-only tablets.
http://stackoverflow.com/questions/5623863/uses-feature-overruling-uses-permission
You'll need to check if the device has telephony with hasSystemFeature:
http://developer.android.com/reference/android/content/pm/PackageManager.html#hasSystemFeature%28java.lang.String%29

**Comment by eyedol** [comment]
Yeah. The android market filters the app out if a device doesn't have the telephony hardware. I'm going to remove the permission for now and then provide an update. @evansims  Thanks for the heads up. I'm on it.

**Comment by eyedol** [comment]
@ptressel That will be a smart fix. Thanks for the link
