### ISSUE TITLE
possible incorrect category data

### ISSUE THREAD

**Issue by ghost** [ushahidi/Ushahidi_Android#87]
The `report_category` table holds the category data for both pending & fetched reports.  
The value for the `report_category.report_id` can be either:
- `incidents._id` if `incidents.pending=1`
- `incidents.incident_id` if `incidents.pending=0`

if we have the following data:

```
table: incidents
_id | incident_id | pending
===========================
0   | 1           | 0              
1   | 0           | 1

table: report_category
category_id | report_id
=======================
1           | 1        
2           | 1 
```

Wouldn't the category data for both incidents be incorrect?

**Comment by eyedol** [comment]
Good catch. Good approach is to add the pending filed. That way we're always sure of manipulating the right data

```
table: report_category
category_id | report_id | pending
=====================================
1           | 1         | 0       
2           | 1         | 1
```

**Updated** Fix incident_id to Pending. That was what I meant to say actually
