### ISSUE TITLE
cannot send report by android app

### ISSUE THREAD

**Issue by aaagneees** [ushahidi/Ushahidi_Android#94]
don't know why, but since 2/3 days when i try to send a report by mobile appears a popup saying that the sending is failed... :( can u help me?
check it on occupysfitto.crowdmap.com but it happens on every map i use...

**Comment by eyedol** [comment]
@aaagneees Does your crowdmap deployment have checkins enabled? Double check. If it's enabled, the mobile app uses that instead.
